// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWEgz-9UFn8nW-RBctExeYkNWY4g2sTo',
    appId: '1:206893229269:web:9c6fbff7ff90e5ec3e2e5c',
    messagingSenderId: '206893229269',
    projectId: 'upsidefinance-flutter-app',
    authDomain: 'upsidefinance-flutter-app.firebaseapp.com',
    storageBucket: 'upsidefinance-flutter-app.appspot.com',
    measurementId: 'G-K5YQ4T7YJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGosVgiVN1_qLgMlElkLS68MxDkV-A1A8',
    appId: '1:206893229269:android:4cf2870673b4ce7f3e2e5c',
    messagingSenderId: '206893229269',
    projectId: 'upsidefinance-flutter-app',
    storageBucket: 'upsidefinance-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSUoiTSuTYn1vFoVyflq0YizGZa0WYfRQ',
    appId: '1:206893229269:ios:db16f3516bd00d4f3e2e5c',
    messagingSenderId: '206893229269',
    projectId: 'upsidefinance-flutter-app',
    storageBucket: 'upsidefinance-flutter-app.appspot.com',
    iosClientId: '206893229269-ac22mqns6tpsbunmkd8h0pavdv490q3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSUoiTSuTYn1vFoVyflq0YizGZa0WYfRQ',
    appId: '1:206893229269:ios:db16f3516bd00d4f3e2e5c',
    messagingSenderId: '206893229269',
    projectId: 'upsidefinance-flutter-app',
    storageBucket: 'upsidefinance-flutter-app.appspot.com',
    iosClientId: '206893229269-ac22mqns6tpsbunmkd8h0pavdv490q3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufFlutterApp',
  );
}
